### ISSUE TITLE
Problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by lucasamparo** [neka-nat/probreg#13]
When I tried to install this repository on my ubuntu version (I can't update this now), I've faced a huge error traceback.

```
Collecting pybind11>=2.2 (from probreg===0.1.7)
  Using cached https://files.pythonhosted.org/packages/4b/4d/ae1c4d8e8b139afa9682054dd42df3b0e3b5c1731287933021b9fd7e9cc4/pybind11-2.4.3-py2.py3-none-any.whl
Collecting open3d-python (from probreg===0.1.7)
  Using cached https://files.pythonhosted.org/packages/3c/8c/45cc3d3096ab19238910212b723df46b845a3c69a86865d50a09e7a6f32e/open3d_python-0.7.0.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting six (from probreg===0.1.7)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting transformations (from probreg===0.1.7)
  Using cached https://files.pythonhosted.org/packages/5c/2c/d8cdf93d6dd61e899500ad2798d5633eb4124eca42186aa92559323a1cd6/transformations-2019.4.22.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: svnversion: not found
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
     int exp (void);
         ^
    _configtest.o: na função `main':
    /tmp/easy_install-u_65z9fb/numpy-1.17.4/_configtest.c:6: referência indefinida para `exp'
    collect2: error: ld returned 1 exit status
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
     int exp (void);
         ^
    _configtest.c:1:20: fatal error: Python.h: Arquivo ou diretório não encontrado
    compilation terminated.
    non-existing path in 'numpy/distutils': 'site.cfg'
    Searching for numpy>=1.11.3
    Reading https://pypi.python.org/simple/numpy/
    Best match: numpy 1.17.4
    Downloading https://files.pythonhosted.org/packages/ff/59/d3f6d46aa1fd220d020bdd61e76ca51f6548c6ad6d24ddb614f4037cf49d/numpy-1.17.4.zip#sha256=f58913e9227400f1395c7b800503ebfdb0772f1c33ff8cb4d6451c06cabdf316
    Processing numpy-1.17.4.zip
    Writing /tmp/easy_install-jgw4vj7m/numpy-1.17.4/setup.cfg
    Running numpy-1.17.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jgw4vj7m/numpy-1.17.4/egg-dist-tmp-k3jg627z
    /bin/sh: 1: svnversion: not found
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
     int exp (void);
         ^
    _configtest.o: na função `main':
    /tmp/easy_install-jgw4vj7m/numpy-1.17.4/_configtest.c:6: referência indefinida para `exp'
    collect2: error: ld returned 1 exit status
    _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
     int exp (void);
         ^
    _configtest.c:1:20: fatal error: Python.h: Arquivo ou diretório não encontrado
    compilation terminated.
    Running from numpy source directory.
    /tmp/easy_install-u_65z9fb/numpy-1.17.4/setup.py:419: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    /tmp/pip-build-nrquw1a1/transformations/setup.py:90: UserWarning: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
      warnings.warn(str(e))
    /tmp/pip-build-nrquw1a1/transformations/setup.py:92: UserWarning: The _transformations C extension module was not built.
    Using a fallback module with limited functionality and performance.
      'The _transformations C extension module was not built.\n'
    Running from numpy source directory.
    /tmp/easy_install-jgw4vj7m/numpy-1.17.4/setup.py:419: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/setup.py", line 444, in <module>
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/setup.py", line 436, in setup_package
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/core.py", line 171, in setup
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 316, in build_extension_sources
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 430, in generate_config_h
      File "numpy/core/setup.py", line 49, in check_types
        Extension('transformations._transformations',
      File "numpy/core/setup.py", line 288, in check_types
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-nrquw1a1/transformations/setup.py", line 88, in <module>
        setup(ext_modules=ext_modules, **setup_args)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/setup.py", line 444, in <module>
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/setup.py", line 436, in setup_package
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/core.py", line 171, in setup
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 316, in build_extension_sources
      File "/tmp/easy_install-u_65z9fb/numpy-1.17.4/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 430, in generate_config_h
      File "numpy/core/setup.py", line 49, in check_types
        Extension('transformations._transformations',
      File "numpy/core/setup.py", line 288, in check_types
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/setup.py", line 444, in <module>
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/setup.py", line 436, in setup_package
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/core.py", line 171, in setup
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 316, in build_extension_sources
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 430, in generate_config_h
      File "numpy/core/setup.py", line 49, in check_types
        Extension('transformations._transformations',
      File "numpy/core/setup.py", line 288, in check_types
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nrquw1a1/transformations/setup.py", line 94, in <module>
        setup(**setup_args)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/setup.py", line 444, in <module>
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/setup.py", line 436, in setup_package
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/core.py", line 171, in setup
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 142, in run
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 316, in build_extension_sources
      File "/tmp/easy_install-jgw4vj7m/numpy-1.17.4/numpy/distutils/command/build_src.py", line 369, in generate_sources
      File "numpy/core/setup.py", line 430, in generate_config_h
      File "numpy/core/setup.py", line 49, in check_types
        Extension('transformations._transformations',
      File "numpy/core/setup.py", line 288, in check_types
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    non-existing path in 'numpy/distutils': 'site.cfg'
```

Someone know how can I fix this?

**Comment by neka-nat** [comment]
Hi @lucasamparo ,
How about installing `python-dev` as described in the error message?

```
sudo apt-get install python-dev
```

**Comment by lucasamparo** [comment]
Oh. Thanks.
Just to point:
```
sudo apt-get install python3.7-dev
```
