### ISSUE TITLE
Installation Error : AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by johnrachwan123** [neka-nat/probreg#2]
Hello, thank you for making this great tool. I ran into a problem while installing the module. I tried using both methods but the result is the same. I also tried using a different PC but it also gave me the same error.
This is the error in question : 

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TV-2-I\Desktop\3d-labeling-tool-Visualization\3d-labeling-tool-Visualization\Python Scripts\probreg\setup.py", line 108, in <module>
        use_omp = _check_for_openmp()
      File "C:\Users\TV-2-I\Desktop\3d-labeling-tool-Visualization\3d-labeling-tool-Visualization\Python Scripts\probreg\setup.py", line 22, in _check_for_openmp
        'CC', distutils.sysconfig.get_config_var('CC')).split()[0]
    AttributeError: 'NoneType' object has no attribute 'split'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1

**Comment by neka-nat** [comment]
Hi,
Thank you for the report.
I fixed the installation for Windows, so please try the installation again.

```
pip install -U probreg
```

**Comment by johnrachwan123** [comment]
Thank you!
