### ISSUE TITLE
 "cannot import name '_math'" problem

### ISSUE THREAD

**Issue by onceforall** [neka-nat/probreg#4]
thanks for what you have done,but during the test, i got the problem "cannot import name '_math'",,i have no idea how to solve this,thanks for your help!

**Comment by neka-nat** [comment]
Thank you for reporting.
If possible, can I see the terminal log during installation and running the test?

**Comment by onceforall** [comment]
The test log as follows:
Testing started at 22:54 ...
D:\python3.5\python.exe "D:\PyCharm 2017.3.4\helpers\pycharm\_jb_unittest_runner.py" --path E:/pychrm-projects/probreg-master/tests/test_cpd.py
Launching unittests with arguments python -m unittest E:/pychrm-projects/probreg-master/tests/test_cpd.py in E:\pychrm-projects\probreg-master\tests



Ran 1 test in 0.000s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "D:\python3.5\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "D:\python3.5\lib\unittest\case.py", line 605, in run
    testMethod()
  File "D:\python3.5\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_cpd
Traceback (most recent call last):
  File "D:\python3.5\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "E:\pychrm-projects\probreg-master\tests\test_cpd.py", line 5, in <module>
    from probreg import cpd
  File "E:\pychrm-projects\probreg-master\probreg\cpd.py", line 8, in <module>
    from . import transformation as tf
  File "E:\pychrm-projects\probreg-master\probreg\transformation.py", line 5, in <module>
    from . import math_utils as mu
  File "E:\pychrm-projects\probreg-master\probreg\math_utils.py", line 3, in <module>
    from . import _math
ImportError: cannot import name '_math'

**Comment by neka-nat** [comment]
Did you execute the following command after cloning from git?
```
git clone https://github.com/neka-nat/probreg.git --recursive
cd probreg
pip install -e .
```
Please execute this and then test.

**Comment by onceforall** [comment]
thanks




| |
贺佳宾（华北电力大学推免生）
邮箱：13261199328@163.com
|

签名由 网易邮箱大师 定制

On 07/08/2019 23:24, neka-nat wrote:

Did you execute the following command after cloning from git?

git clone https://github.com/neka-nat/probreg.git --recursive
cd probreg
pip install -e .


Please execute this and then test.
