### ISSUE TITLE
error when import probreg after pip installtion on ubuntu 20.04 + python3.6

### ISSUE THREAD

**Issue by szx0112** [neka-nat/probreg#98]
run in conda environment

`from probreg import cpd, filterreg, gmmtree, l2dist_regs, features`

Error message show below:

```
Traceback (most recent call last):
  File "/home/szx/PycharmProjects/test_project/run.py", line 23, in <module>
    from probreg import cpd, filterreg, gmmtree, l2dist_regs, features
  File "/home/szx/anaconda3/envs/pipe_4cams/lib/python3.6/site-packages/probreg/__init__.py", line 1, in <module>
    from . import bcpd, callbacks, cpd, filterreg, gmmtree, l2dist_regs, log, math_utils, transformation
  File "/home/szx/anaconda3/envs/pipe_4cams/lib/python3.6/site-packages/probreg/filterreg.py", line 16, in <module>
    from . import se3_op as so
  File "/home/szx/anaconda3/envs/pipe_4cams/lib/python3.6/site-packages/probreg/se3_op.py", line 1
    from __future__ import annotations, division, print_function
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by neka-nat** [comment]
Can you try with python 3.7 or higher?
https://peps.python.org/pep-0563/#enabling-the-future-behavior-in-python-3-7
